### PR TITLE
Multi selections should union within the same unit and intersect across units.

### LINKED ISSUE #55: Multi selections across units
A multi selection adds a tuple to the store for every point a user interacts with (e.g., clicks on). Within a unit, the expected set of "selected members" of a multi selection is thus the union of these tuples. This behaviour should persist when a multi selection participates within a composite view.

Currently, however, the `op` that is passed to the `vlSelection` method determines the behaviour across _all_ tuples within a selection's store. So, in the case of layered crossfilter with a multi selection, setting `resolve: "intersect"` (as with a single or interval selection) fails as one cannot select multiple bars within the same unit. 

Instead, the expected behaviour should be that I can select multiple bars within the same unit which then get intersected with multiple bars selected across all other units.

### PR DESCRIPTION
**Pull request by arvind**
This PR fixes #55. The `point` selection functions have been broken up into separate `single` and `multi` functions. If a `multi` function is called with an `intersect` parameter, an index is built on the selection store over the `unit` field. 

The predicate function uses this index to conduct inclusion testing. If we've missed against all selections in the current unit, return false; otherwise keep testing. The materialization function first materializes each unit's selection and then intersects them overall.

### CODE REVIEW

File: src/parsers/expression/selection.js [hunk 1]
```diff
@@ -99,14 +109,34 @@ function vlSelection(name, datum, op, unit, scope, test) {
 
 // Assumes point selection tuples are of the form:
 // {unit: string, encodings: array<string>, fields: array<string>, values: array<*>, bins: object}
-export function vlPoint(name, datum, op, unit, scope) {
-  return vlSelection.call(this, name, datum, op, unit, scope, testPoint);
+export function vlSingle(name, datum, op) {
+  return vlSelection.call(this, name, datum, op, testPoint);
+}
+
+export function vlMulti(name, datum, op) {
```
Comment (jheer) [inline src/parsers/expression/selection.js]: Looks like this is identical to `vlSingle`. Why the redundant definition and export?

File: src/parsers/expression/selection.js [hunk 2]
```diff
@@ -135,17 +166,40 @@ export function vlPointDomain(name, encoding, field, op) {
...
+      acc.push({unit: entry.unit, value: entry.values[index]});
+      return acc;
+    }, []);
+  }
 
   return continuous ? continuousDomain(values, op) : discreteDomain(values, op);
 }
 
+export var vlSingleDomain = vlPointDomain;
+export var vlMultiDomain = vlPointDomain;
```
Comment (jheer) [inline src/parsers/expression/selection.js]: Identical exports. Why not just export `vlPointDomain`?

Comment (arvind) [reply src/parsers/expression/selection.js]: For both this and the above comment, it's to use a different visitor (one that adds an index field) for multi selections. I picked this approach because it yields cleaner paths in Vega-Lite.  Some alternatives would be: (1) consolidate to a single function but pass a `type` parameter in; (2) always register an index for all point selections.

Comment (jheer) [reply src/parsers/expression/selection.js]: Function definition and expression function registration are separate. Why not do something like this instead?

```js
expressionFunction('vlSingle', vlPoint, dataVisitor);
expressionFunction('vlSingleDomain', vlPointDomain, dataVisitor);
expressionFunction('vlMulti', vlPoint, vlMultiVisitor);
expressionFunction('vlMultiDomain', vlPointDomain, vlMultiVisitor);
```

Comment (arvind) [reply src/parsers/expression/selection.js]: Facepalm. Of course!

Comment (arvind) [reply src/parsers/expression/selection.js]: Fixed.

File: src/parsers/expression/codegen.js [hunk 3]
```diff
@@ -122,9 +122,11 @@ expressionFunction('geoBounds', geoBounds, scaleVisitor);
 expressionFunction('geoCentroid', geoCentroid, scaleVisitor);
 expressionFunction('indata', indata, indataVisitor);
 expressionFunction('data', data, dataVisitor);
-expressionFunction('vlPoint', vlPoint, dataVisitor);
+expressionFunction('vlSingle', vlPoint, dataVisitor);
+expressionFunction('vlSingleDomain', vlPointDomain, dataVisitor);
+expressionFunction('vlMulti', vlPoint, vlMultiVisitor);
+expressionFunction('vlMultiDomain', vlPointDomain, dataVisitor);
```
Comment (jheer) [inline src/parsers/expression/codegen.js]: Should `vlMultiDomain` have a `dataVisitor` or a `vlMultiVisitor`?

File: src/parsers/expression/selection.js [hunk 4]
```diff
@@ -135,13 +161,33 @@ export function vlPointDomain(name, encoding, field, op) {
...
+    }, {});
+
+    values = Object.keys(units).reduce(function(acc, unit) {
+       acc.push({
+        unit: unit,
+        value: continuous ? continuousDomain(units[unit], UNION) :
+          discreteDomain(units[unit], UNION)
+      });
+      return acc;
+    }, []);
```
Comment (jheer) [inline src/parsers/expression/selection.js]: Why use `reduce` here? It looks like this could be done more parsimoniously with `map`.

File: src/parsers/expression/selection.js [hunk 5]
```diff
@@ -135,13 +161,33 @@ export function vlPointDomain(name, encoding, field, op) {
...
+  } else {
+    values = entries.reduce(function(acc, entry) {
+      acc.push({unit: entry.unit, value: entry.values[index]});
+      return acc;
+    }, []);
```
Comment (jheer) [inline src/parsers/expression/selection.js]: Again: Why use `reduce` here? It looks like this could be done more parsimoniously with `map`.

**Comment by arvind** [comment]
Thanks for the comments, @jheer. Changes pushed!

**Comment by arvind** [comment]
Thanks for the comments @jheer. Changes pushed, and fixed some other bugs in the process too.
